/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <pokemongo/GKGameCenterControllerDelegate.h>

@class GKGameCenterViewController, NSString;

@interface AchievementWrapper : UIViewController <GKGameCenterControllerDelegate> {

	GKGameCenterViewController* m_AchievementsView;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)reportProgressWithCache:(double)arg1 withIdentifier:(id)arg2 ;
+(void)reportSingleAchievement:(id)arg1 completion:(/*^block*/id)arg2 ;
+(void)loadAchievementDescriptions;
+(void)loadAchievements;
+(void)reportProgress:(double)arg1 withIdentifier:(id)arg2 ;
-(void)showAchievementsUI;
-(void)gameCenterViewControllerDidFinish:(id)arg1 ;
@end

