/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/VideoPlayerDelegate.h>
#import <UIKit/UIViewControllerTransitioningDelegate.h>

@class AVPlayerViewController, VideoPlayer, CancelOnTouchView, UIColor, NSString;

@interface AVKitVideoPlayback : NSObject <VideoPlayerDelegate, UIViewControllerTransitioningDelegate> {

	AVPlayerViewController* videoViewController;
	VideoPlayer* videoPlayer;
	CancelOnTouchView* cancelOnTouchView;
	UIColor* bgColor;
	NSString* videoGravity;
	BOOL showControls;
	BOOL cancelOnTouch;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)InitClass;
+(BOOL)IsSupported;
-(void)actuallyStartTheMovie:(id)arg1 ;
-(void)onPlayerReady;
-(void)onPlayerDidFinishPlayingVideo;
-(void)onPlayerError:(id)arg1 ;
-(id)initAndPlay:(id)arg1 bgColor:(id)arg2 showControls:(BOOL)arg3 videoGravity:(id)arg4 cancelOnTouch:(BOOL)arg5 ;
-(void)dealloc;
-(id)animationControllerForDismissedController:(id)arg1 ;
-(void)handleTap:(id)arg1 ;
-(void)finish;
@end

