/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/pokemongo-Structs.h>
#import <pokemongo/AVCaptureVideoDataOutputSampleBufferDelegate.h>

@class AVCaptureDevice, AVCaptureSession, AVCaptureDeviceInput, AVCaptureVideoDataOutput, NSString;

@interface CameraCaptureController : NSObject <AVCaptureVideoDataOutputSampleBufferDelegate> {

	AVCaptureDevice* _captureDevice;
	AVCaptureSession* _captureSession;
	AVCaptureDeviceInput* _captureInput;
	AVCaptureVideoDataOutput* _captureOutput;
	CMVideoSampling* _cmVideoSampling;
	void* _userData;
	unsigned long long _width;
	unsigned long long _height;

}

@property (nonatomic,retain) AVCaptureDevice * captureDevice;                       //@synthesize captureDevice=_captureDevice - In the implementation block
@property (nonatomic,retain) AVCaptureSession * captureSession;                     //@synthesize captureSession=_captureSession - In the implementation block
@property (nonatomic,retain) AVCaptureDeviceInput * captureInput;                   //@synthesize captureInput=_captureInput - In the implementation block
@property (nonatomic,retain) AVCaptureVideoDataOutput * captureOutput;              //@synthesize captureOutput=_captureOutput - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setCaptureInput:(AVCaptureDeviceInput *)arg1 ;
-(void)setCaptureOutput:(AVCaptureVideoDataOutput *)arg1 ;
-(AVCaptureVideoDataOutput *)captureOutput;
-(AVCaptureDeviceInput *)captureInput;
-(id)pickFrameRateRange:(float)arg1 ;
-(id)pickPresetFromWidth:(int)arg1 height:(int)arg2 ;
-(BOOL)initCapture:(id)arg1 width:(int)arg2 height:(int)arg3 fps:(float)arg4 ;
-(void)stop;
-(void)start;
-(void)pause;
-(void)setCaptureDevice:(AVCaptureDevice *)arg1 ;
-(AVCaptureDevice *)captureDevice;
-(void)captureOutput:(id)arg1 didOutputSampleBuffer:(opaqueCMSampleBufferRef)arg2 fromConnection:(id)arg3 ;
-(AVCaptureSession *)captureSession;
-(void)setCaptureSession:(AVCaptureSession *)arg1 ;
@end

