/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/CRConnectionHandler.h>

@interface CRAppLoadedHandler : CRConnectionHandler
-(void)handleResponse:(long long)arg1 andData:(id)arg2 ;
-(void)processResponse:(id)arg1 ;
-(void)useStoredSettings;
-(void)recievedInternalCrashReporting:(id)arg1 ;
-(void)receivedSettings:(id)arg1 ;
-(void)receivedRateMeSettings:(id)arg1 ;
-(void)handleError:(id)arg1 ;
@end

