/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSNumber, NSString;

@interface CRAppInfo : NSObject {

	BOOL _hasAlternateVersion;
	NSNumber* _isPirated;
	NSString* _bundleVersion;
	NSString* _marketingVersion;
	NSString* _bundleIdentifier;
	NSString* _alternateVersion;

}

@property (readonly) NSNumber * isPirated;                     //@synthesize isPirated=_isPirated - In the implementation block
@property (readonly) NSString * bundleVersion;                 //@synthesize bundleVersion=_bundleVersion - In the implementation block
@property (readonly) NSString * marketingVersion;              //@synthesize marketingVersion=_marketingVersion - In the implementation block
@property (readonly) NSString * bundleIdentifier;              //@synthesize bundleIdentifier=_bundleIdentifier - In the implementation block
@property (readonly) BOOL hasAlternateVersion;                 //@synthesize hasAlternateVersion=_hasAlternateVersion - In the implementation block
@property (retain) NSString * alternateVersion;                //@synthesize alternateVersion=_alternateVersion - In the implementation block
+(id)appInfo;
-(NSNumber *)isPirated;
-(BOOL)hasAlternateVersion;
-(NSString *)alternateVersion;
-(NSString *)marketingVersion;
-(void)setAlternateVersion:(NSString *)arg1 ;
-(id)init;
-(NSString *)bundleIdentifier;
-(NSString *)bundleVersion;
-(id)appVersion;
@end

