/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface CRAppLocator : NSObject {

	NSString* _apiURL;
	NSString* _apmURL;
	NSString* _appLoadURL;
	NSString* _txnURL;

}

@property (nonatomic,copy,readonly) NSString * apiURL;                  //@synthesize apiURL=_apiURL - In the implementation block
@property (nonatomic,copy,readonly) NSString * apmURL;                  //@synthesize apmURL=_apmURL - In the implementation block
@property (nonatomic,copy,readonly) NSString * appLoadURL;              //@synthesize appLoadURL=_appLoadURL - In the implementation block
@property (nonatomic,copy,readonly) NSString * txnURL;                  //@synthesize txnURL=_txnURL - In the implementation block
-(NSString *)txnURL;
-(id)initWithAppId:(id)arg1 ;
-(id)getDomainFromAppId:(id)arg1 ;
-(NSString *)apiURL;
-(NSString *)apmURL;
-(NSString *)appLoadURL;
@end

