/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/CRPart.h>

@class NSData;

@interface CRDataPart : CRPart {

	NSData* _partData;

}

@property (retain) NSData * partData;              //@synthesize partData=_partData - In the implementation block
-(id)initWithName:(id)arg1 andFilename:(id)arg2 andData:(id)arg3 ;
-(void)setPartData:(NSData *)arg1 ;
-(NSData *)partData;
-(void)serializeTo:(id)arg1 ;
@end

