/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <pokemongo/pokemongo-Structs.h>
@class NSString;

@interface CRDetectedClass : NSObject {

	BOOL _isNSObjectSubclass;
	BOOL _isWebViewSubclass;
	BOOL _isViewControllerSubclass;
	NSString* _name;

}

@property (nonatomic,readonly) NSString * name;                            //@synthesize name=_name - In the implementation block
@property (nonatomic,readonly) BOOL isNSObjectSubclass;                    //@synthesize isNSObjectSubclass=_isNSObjectSubclass - In the implementation block
@property (nonatomic,readonly) BOOL isWebViewSubclass;                     //@synthesize isWebViewSubclass=_isWebViewSubclass - In the implementation block
@property (nonatomic,readonly) BOOL isViewControllerSubclass;              //@synthesize isViewControllerSubclass=_isViewControllerSubclass - In the implementation block
+(id)detectedClassWithFoundClass:(const cr_found_class_t*)arg1 ;
-(id)initWithFoundClass:(const cr_found_class_t*)arg1 ;
-(Class)getClass;
-(BOOL)isNSObjectSubclass;
-(BOOL)isWebViewSubclass;
-(BOOL)isViewControllerSubclass;
-(NSString *)name;
@end

