/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableDictionary;

@interface CRDevice : NSObject {

	NSMutableDictionary* _deviceInfo;

}

@property (nonatomic,copy) NSMutableDictionary * deviceInfo;              //@synthesize deviceInfo=_deviceInfo - In the implementation block
+(id)deviceFromCurrentDevice;
+(id)deviceFromPersistentState:(id)arg1 ;
+(id)deviceWithDummyInfo;
-(id)freeDiskSpace;
-(id)carrier;
-(id)initFromDeviceInfoDictionary:(id)arg1 ;
-(id)initFromCurrentDevice;
-(id)initFromPersistentState:(id)arg1 ;
-(void)flushToPersistentState:(id)arg1 ;
-(void)updateOrientation;
-(BOOL)isEqual:(id)arg1 ;
-(id)description;
-(id)systemVersion;
-(id)model;
-(id)systemName;
-(id)batteryLevel;
-(id)locale;
-(id)asDictionary;
-(void)setDeviceInfo:(NSMutableDictionary *)arg1 ;
-(NSMutableDictionary *)deviceInfo;
-(id)memoryUsage;
-(id)platform;
-(id)mobileCountryCode;
-(id)mobileNetworkCode;
@end

