/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface CRFilter : NSObject {

	unsigned long long _filterType;
	NSString* _token;

}

@property (readonly) unsigned long long filterType;              //@synthesize filterType=_filterType - In the implementation block
@property (copy) NSString * token;                               //@synthesize token=_token - In the implementation block
+(id)applyFilter:(unsigned long long)arg1 ToURL:(id)arg2 ;
+(id)queryOnlyFilterWithString:(id)arg1 ;
+(id)queryPreservingFilterWithString:(id)arg1 ;
+(id)filterWithString:(id)arg1 ;
-(BOOL)doesMatch:(id)arg1 ;
-(id)initWithString:(id)arg1 andFilterType:(unsigned long long)arg2 ;
-(id)initWithString:(id)arg1 ;
-(unsigned long long)filterType;
-(NSString *)token;
-(void)setToken:(NSString *)arg1 ;
@end

