/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <pokemongo/pokemongo-Structs.h>
@class NSString, NSMutableArray;

@interface CRNetStatDispatch : NSObject {

	dispatch_queue_sRef _queue;
	NSString* _ignoreEndpoint;
	NSMutableArray* _blacklistFilters;
	NSMutableArray* _otherFilters;
	NSMutableArray* _observers;

}

@property (assign,nonatomic) dispatch_queue_sRef queue;               //@synthesize queue=_queue - In the implementation block
@property (retain) NSString * ignoreEndpoint;                         //@synthesize ignoreEndpoint=_ignoreEndpoint - In the implementation block
@property (retain) NSMutableArray * blacklistFilters;                 //@synthesize blacklistFilters=_blacklistFilters - In the implementation block
@property (retain) NSMutableArray * otherFilters;                     //@synthesize otherFilters=_otherFilters - In the implementation block
@property (nonatomic,retain) NSMutableArray * observers;              //@synthesize observers=_observers - In the implementation block
-(void)synchronousLogNetworkRequest:(id)arg1 ;
-(void)logNetworkRequest:(id)arg1 ;
-(id)initWithFilters:(id)arg1 andBaseURL:(id)arg2 andEndpoint:(id)arg3 ;
-(NSString *)ignoreEndpoint;
-(void)setIgnoreEndpoint:(NSString *)arg1 ;
-(NSMutableArray *)blacklistFilters;
-(void)setBlacklistFilters:(NSMutableArray *)arg1 ;
-(NSMutableArray *)otherFilters;
-(void)setOtherFilters:(NSMutableArray *)arg1 ;
-(void)registerObserver:(id)arg1 ;
-(dispatch_queue_sRef)queue;
-(void)setQueue:(dispatch_queue_sRef)arg1 ;
-(void)dealloc;
-(void)setObservers:(NSMutableArray *)arg1 ;
-(NSMutableArray *)observers;
-(void)addFilter:(id)arg1 ;
@end

