/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface CRPart : NSObject {

	NSString* _name;
	NSString* _filename;
	NSString* _contentType;

}

@property (retain) NSString * name;                     //@synthesize name=_name - In the implementation block
@property (retain) NSString * filename;                 //@synthesize filename=_filename - In the implementation block
@property (retain) NSString * contentType;              //@synthesize contentType=_contentType - In the implementation block
-(id)initWithName:(id)arg1 andFilename:(id)arg2 andContentType:(id)arg3 ;
-(void)setContentType:(NSString *)arg1 ;
-(void)setName:(NSString *)arg1 ;
-(NSString *)name;
-(NSString *)contentType;
-(NSString *)filename;
-(void)setFilename:(NSString *)arg1 ;
-(void)serializeTo:(id)arg1 ;
@end

