/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface CRPreferences : NSObject {

	NSString* _critterKey;

}

@property (nonatomic,retain) NSString * critterKey;              //@synthesize critterKey=_critterKey - In the implementation block
-(id)getValueWithKey:(id)arg1 andDictionaryName:(id)arg2 ;
-(void)storeValue:(id)arg1 forKey:(id)arg2 forDictionary:(id)arg3 ;
-(id)getRootDict;
-(void)doStoreValue:(id)arg1 forKey:(id)arg2 forDictionary:(id)arg3 wasWritten:(BOOL*)arg4 ;
-(void)storeValue:(id)arg1 forKey:(id)arg2 forDictionary:(id)arg3 wasWritten:(BOOL*)arg4 ;
-(id)initWithAppId:(id)arg1 ;
-(void)clearValueForKey:(id)arg1 andDictionary:(id)arg2 ;
-(NSString *)critterKey;
-(void)setCritterKey:(NSString *)arg1 ;
-(id)describe;
-(void)reset;
-(id)getDict:(id)arg1 ;
@end

