/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/pokemongo-Structs.h>
#import <Foundation/NSProxy.h>
#import <UIKit/UIWebViewDelegate.h>

@class NSSet, NSString;

@interface CRUIWebViewDelegateProxy : NSProxy <UIWebViewDelegate> {

	id _delegate;
	NSSet* _selectorsWeRespondTo;

}

@property (assign,nonatomic) id delegate;                               //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) NSSet * selectorsWeRespondTo;              //@synthesize selectorsWeRespondTo=_selectorsWeRespondTo - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)initWithFrameForUIWebView:(id)arg1 frame:(CGRect)arg2 dispatch:(id)arg3 ;
+(void)replaceUIWebViewmethod:(SEL)arg1 withSwizzledSelector:(SEL)arg2 implementedBlock:(id)arg3 ;
+(id)initWithCoderForUIWebView:(id)arg1 coder:(id)arg2 dispatch:(id)arg3 ;
+(id)delegateForUIWebView:(id)arg1 dispatch:(id)arg2 ;
+(void)setDelegateForUIWebView:(id)arg1 delegate:(id)arg2 dispatch:(id)arg3 ;
+(void)swizzleUIWebViewInitWithFrameAndDispatch:(id)arg1 ;
+(void)swizzleUIWebViewInitWithCoderAndDispatch:(id)arg1 ;
+(void)swizzleUIWebViewDelegateWithDispatch:(id)arg1 ;
+(void)swizzleUIWebViewSetDelegateWithDispatch:(id)arg1 ;
+(void)traverseUI;
+(void)traverseView:(id)arg1 ;
+(id)performSwizzledUIWebViewDelegateSelector:(id)arg1 ;
+(void)performSwizzledUIWebViewSetDelegateSelector:(id)arg1 withProxy:(id)arg2 ;
+(id)performSwizzledUIWebViewInitWithFrameSelector:(id)arg1 withFrame:(CGRect)arg2 ;
+(id)performSwizzledUIWebViewInitWithCoderSelector:(id)arg1 withCoder:(id)arg2 ;
+(id)proxyFromWebView:(id)arg1 dispatch:(id)arg2 ;
+(void)instrumentUIWebViewWithDispatch:(id)arg1 ;
+(void)uninstrumentUIWebView;
+(BOOL)isInstrumented;
+(BOOL)respondsToSelector:(SEL)arg1 ;
-(NSSet *)selectorsWeRespondTo;
-(void)setSelectorsWeRespondTo:(NSSet *)arg1 ;
-(id)initWithDelegate:(id)arg1 dispatch:(id)arg2 ;
-(void)addAssociationToWebView:(id)arg1 ;
-(void)setDelegate:(id)arg1 ;
-(BOOL)respondsToSelector:(SEL)arg1 ;
-(NSString *)description;
-(NSString *)debugDescription;
-(id)delegate;
-(id)methodSignatureForSelector:(SEL)arg1 ;
-(void)forwardInvocation:(id)arg1 ;
-(void)webView:(id)arg1 didFailLoadWithError:(id)arg2 ;
-(BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3 ;
-(void)webViewDidFinishLoad:(id)arg1 ;
@end

