/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/pokemongo-Structs.h>
#import <Foundation/NSProxy.h>
#import <libobjc.A.dylib/WKNavigationDelegate.h>

@class NSSet, CRRequestState, NSTimer, CRNetStatDispatch, NSString;

@interface CRWKNavigationDelegateProxy : NSProxy <WKNavigationDelegate> {

	id _navigationDelegate;
	NSSet* _selectorsWeRespondTo;
	CRRequestState* _reqState;
	NSTimer* _timer;
	CRNetStatDispatch* _dispatch;

}

@property (assign,nonatomic,__weak) id navigationDelegate;              //@synthesize navigationDelegate=_navigationDelegate - In the implementation block
@property (nonatomic,retain) NSSet * selectorsWeRespondTo;              //@synthesize selectorsWeRespondTo=_selectorsWeRespondTo - In the implementation block
@property (nonatomic,retain) CRRequestState * reqState;                 //@synthesize reqState=_reqState - In the implementation block
@property (nonatomic,retain) NSTimer * timer;                           //@synthesize timer=_timer - In the implementation block
@property (nonatomic,retain) CRNetStatDispatch * dispatch;              //@synthesize dispatch=_dispatch - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)traverseUI;
+(void)traverseView:(id)arg1 ;
+(id)proxyFromWebView:(id)arg1 dispatch:(id)arg2 ;
+(BOOL)isInstrumented;
+(void)instrumentWKWebViewWithDispatch:(id)arg1 ;
+(id)initWithFrameForWKWebView:(id)arg1 frame:(CGRect)arg2 configuration:(id)arg3 dispatch:(id)arg4 ;
+(void)replaceWKWebViewmethod:(SEL)arg1 withSwizzledSelector:(SEL)arg2 implementedBlock:(id)arg3 ;
+(id)navigationDelegateForWKWebView:(id)arg1 dispatch:(id)arg2 ;
+(void)setNavigationDelegateForWKWebView:(id)arg1 navigationDelegate:(id)arg2 dispatch:(id)arg3 ;
+(void)swizzleWKWebViewInitWithFrameAndDispatch:(id)arg1 ;
+(void)swizzleWKWebViewNavigationDelegateWithDispatch:(id)arg1 ;
+(void)swizzleWKWebViewSetNavigationDelegateWithDispatch:(id)arg1 ;
+(id)performSwizzledWKWebViewNavigationDelegateSelector:(id)arg1 ;
+(void)performSwizzledWKWebViewSetNavigationDelegateSelector:(id)arg1 withProxy:(id)arg2 ;
+(id)performSwizzledWKWebViewInitWithFrameSelector:(id)arg1 withFrame:(CGRect)arg2 withConfig:(id)arg3 ;
+(void)uninstrumentWKWebView;
+(BOOL)respondsToSelector:(SEL)arg1 ;
-(NSSet *)selectorsWeRespondTo;
-(void)setSelectorsWeRespondTo:(NSSet *)arg1 ;
-(void)addAssociationToWebView:(id)arg1 ;
-(void)setReqState:(CRRequestState *)arg1 ;
-(void)setDispatch:(CRNetStatDispatch *)arg1 ;
-(CRRequestState *)reqState;
-(id)initWithNavigationDelegate:(id)arg1 dispatch:(id)arg2 ;
-(BOOL)respondsToSelector:(SEL)arg1 ;
-(NSString *)description;
-(NSString *)debugDescription;
-(id)methodSignatureForSelector:(SEL)arg1 ;
-(void)forwardInvocation:(id)arg1 ;
-(void)setTimer:(NSTimer *)arg1 ;
-(NSTimer *)timer;
-(id)navigationDelegate;
-(void)setNavigationDelegate:(id)arg1 ;
-(void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(/*^block*/id)arg3 ;
-(void)webView:(id)arg1 decidePolicyForNavigationResponse:(id)arg2 decisionHandler:(/*^block*/id)arg3 ;
-(void)webView:(id)arg1 didFinishNavigation:(id)arg2 ;
-(void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3 ;
-(CRNetStatDispatch *)dispatch;
@end

