/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMapTable, DisplayConnection;

@interface DisplayManager : NSObject {

	NSMapTable* _displayConnection;
	DisplayConnection* _mainDisplay;
	unsigned long long displayCount;

}

@property (nonatomic,readonly) DisplayConnection * mainDisplay;              //@synthesize mainDisplay=_mainDisplay - In the implementation block
@property (nonatomic,readonly) unsigned long long displayCount; 
+(id)Instance;
+(void)Initialize;
-(void)endFrameRendering;
-(void)registerScreen:(id)arg1 ;
-(void)enumerateDisplaysWithBlock:(/*^block*/id)arg1 ;
-(void)updateDisplayListInUnity;
-(unsigned long long)displayCount;
-(BOOL)displayAvailable:(id)arg1 ;
-(void)startFrameRendering;
-(id)init;
-(id)objectForKeyedSubscript:(id)arg1 ;
-(DisplayConnection *)mainDisplay;
-(id)display:(id)arg1 ;
-(void)present;
-(void)screenDidConnect:(id)arg1 ;
-(void)screenDidDisconnect:(id)arg1 ;
@end

