/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSString;


@protocol GTMFetcherAuthorizationProtocol <NSObject>
@property (readonly) NSString * userEmail; 
@property (readonly) BOOL canAuthorize; 
@property (assign) BOOL shouldAuthorizeAllRequests; 
@property (__weak) id<GTMSessionFetcherServiceProtocol> fetcherService; 
@optional
-(BOOL)shouldAuthorizeAllRequests;
-(id<GTMSessionFetcherServiceProtocol>)fetcherService;
-(void)authorizeRequest:(id)arg1 completionHandler:(/*^block*/id)arg2;
-(BOOL)primeForRefresh;
-(BOOL)canAuthorize;
-(void)setShouldAuthorizeAllRequests:(BOOL)arg1;
-(void)setFetcherService:(id)arg1;

@required
-(void)stopAuthorization;
-(void)authorizeRequest:(id)arg1 delegate:(id)arg2 didFinishSelector:(SEL)arg3;
-(void)stopAuthorizationForRequest:(id)arg1;
-(BOOL)isAuthorizingRequest:(id)arg1;
-(BOOL)isAuthorizedRequest:(id)arg1;
-(NSString *)userEmail;

@end

