/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface GTMOAuth2Keychain : NSObject
+(id)defaultKeychain;
+(id)keychainQueryForService:(id)arg1 account:(id)arg2 ;
+(void)setDefaultKeychain:(id)arg1 ;
-(id)passwordForService:(id)arg1 account:(id)arg2 error:(id*)arg3 ;
-(BOOL)removePasswordForService:(id)arg1 account:(id)arg2 error:(id*)arg3 ;
-(BOOL)setPassword:(id)arg1 forService:(id)arg2 accessibility:(void*)arg3 account:(id)arg4 error:(id*)arg5 ;
-(id)keychainQueryForService:(id)arg1 account:(id)arg2 ;
-(id)keyForService:(id)arg1 account:(id)arg2 ;
@end

