/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSOperationQueue;


@protocol GTMSessionFetcherServiceProtocol <NSObject>
@property (retain) NSObject*<OS_dispatch_queue> callbackQueue; 
@property (assign) BOOL reuseSession; 
@property (readonly) NSOperationQueue * delegateQueue; 
@required
-(id)fetcherWithRequest:(id)arg1;
-(id)sessionForFetcherCreation;
-(void)fetcherDidCreateSession:(id)arg1;
-(BOOL)fetcherShouldBeginFetching:(id)arg1;
-(void)fetcherDidBeginFetching:(id)arg1;
-(void)fetcherDidStop:(id)arg1;
-(BOOL)isDelayingFetcher:(id)arg1;
-(BOOL)reuseSession;
-(void)setReuseSession:(BOOL)arg1;
-(NSOperationQueue *)delegateQueue;
-(id)session;
-(id)sessionDelegate;
-(void)setCallbackQueue:(id)arg1;
-(NSObject*<OS_dispatch_queue>)callbackQueue;

@end

