/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <UIKit/UIWebViewDelegate.h>

@class NSURL, NSString;

@interface GTMSessionFetcherLoggingWebViewController : UIViewController <UIWebViewDelegate> {

	BOOL opensScrolledToEnd_;
	NSURL* htmlURL_;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithURL:(id)arg1 title:(id)arg2 opensScrolledToEnd:(BOOL)arg3 ;
-(void)didTapBackButton:(id)arg1 ;
-(void)loadView;
-(void)viewDidLoad;
-(id)webView;
-(void)webViewDidFinishLoad:(id)arg1 ;
@end

