/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/UnityViewControllerListener.h>

@class MPMoviePlayerController, CancelOnTouchView, UIColor, NSString;

@interface MPVideoPlayback : NSObject <UnityViewControllerListener> {

	MPMoviePlayerController* moviePlayer;
	CancelOnTouchView* cancelOnTouchView;
	UIColor* bgColor;
	long long controlMode;
	long long scalingMode;
	BOOL cancelOnTouch;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)viewDidLayoutSubviews:(id)arg1 ;
-(void)actuallyStartTheMovie:(id)arg1 ;
-(void)moviePlayBackDidFinish:(id)arg1 ;
-(void)moviePlayBackSourceTypeAvailable:(id)arg1 ;
-(void)moviePlayBackMediaTypesAvailable:(id)arg1 ;
-(void)moviePlayBackNaturalSizeAvailable:(id)arg1 ;
-(void)audioRouteChanged:(id)arg1 ;
-(id)initAndPlay:(id)arg1 bgColor:(id)arg2 controls:(long long)arg3 scaling:(long long)arg4 cancelOnTouch:(BOOL)arg5 ;
-(void)dealloc;
-(void)finish;
@end

