/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/pokemongo-Structs.h>
#import <libobjc.A.dylib/CLLocationManagerDelegate.h>

@protocol OS_dispatch_queue;
@class CLLocationManager, NSObject, NSString;

@interface NIAIosLocationManager : NSObject <CLLocationManagerDelegate> {

	LocationUpdate* _locationProto;
	CLLocationManager* _locationManager;
	NSObject*<OS_dispatch_queue> _work_queue;
	LocationProvider* _locationProvider;
	LocationParameters _locationParameters;

}

@property (assign,nonatomic) LocationProvider* locationProvider;                 //@synthesize locationProvider=_locationProvider - In the implementation block
@property (assign,nonatomic) LocationParameters locationParameters;              //@synthesize locationParameters=_locationParameters - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setLocationParameters:(LocationParameters)arg1 ;
-(int)requestLocationPermissions;
-(LocationParameters)locationParameters;
-(double)desiredAccuracy;
-(void)setLocationProvider:(LocationProvider*)arg1 ;
-(LocationProvider*)locationProvider;
-(void)locationManager:(id)arg1 didUpdateLocations:(id)arg2 ;
-(void)dealloc;
-(id)init;
-(void)stop;
-(void)start;
-(void)startUpdating;
-(void)locationManager:(id)arg1 didUpdateHeading:(id)arg2 ;
-(void)locationManager:(id)arg1 didFailWithError:(id)arg2 ;
@end

