/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <pokemongo/pokemongo-Structs.h>
@class CMMotionActivityManager, NSOperationQueue;

@interface NIAIosActivityManager : NSObject {

	Activity* _userActivity;
	CMMotionActivityManager* _activityManager;
	NSOperationQueue* _activityQueue;
	IosActivityProvider* _activityProvider;

}

@property (assign,nonatomic) IosActivityProvider* activityProvider;              //@synthesize activityProvider=_activityProvider - In the implementation block
-(int)mapConfidenceToInt:(long long)arg1 ;
-(IosActivityProvider*)activityProvider;
-(void)handleActivityUpdate:(id)arg1 ;
-(void)checkAuthorization:(/*^block*/id)arg1 ;
-(void)setActivityProvider:(IosActivityProvider*)arg1 ;
-(void)setLocationProvider:(IosActivityProvider*)arg1 ;
-(void)dealloc;
-(id)init;
-(void)stop;
-(void)start;
@end

