/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class GTMOAuth2Authentication, NSString, GTMSessionFetcherService;

@interface NIAIosAuthenticationManager : NSObject {

	GTMOAuth2Authentication* _auth;
	NSString* _clientAuthToken;
	GTMSessionFetcherService* _fetcherService;

}
-(void)getAccountOrLogin:(id)arg1 clientSecret:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)clearAuth;
-(void)refreshIdTokenWithCompletion:(/*^block*/id)arg1 ;
-(id)defaultSourceString;
-(id)init;
-(id)description;
-(id)navigationController;
-(id)userEmail;
@end

