/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <pokemongo/pokemongo-Structs.h>
@class CMMotionManager, NSOperationQueue;

@interface NIAIosSensorManager : NSObject {

	SensorUpdate* _sensorProto;
	CMMotionManager* _motionManager;
	NSOperationQueue* _sensorQueue;
	IosSensorProvider* _sensorProvider;

}

@property (assign,nonatomic) IosSensorProvider* sensorProvider;              //@synthesize sensorProvider=_sensorProvider - In the implementation block
-(void)setSensorProvider:(IosSensorProvider*)arg1 ;
-(void)processDeviceMotion:(id)arg1 error:(id)arg2 ;
-(IosSensorProvider*)sensorProvider;
-(void)dealloc;
-(id)init;
-(void)stop;
-(void)start;
@end

