/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/CBCentralManagerDelegate.h>
#import <pokemongo/CBPeripheralDelegate.h>

@protocol OS_dispatch_queue;
@class NSMutableDictionary, CBCentralManager, NSObject, NSString;

@interface PGPBluetoothDriver : NSObject <CBCentralManagerDelegate, CBPeripheralDelegate> {

	BOOL _poweredOn;
	NSMutableDictionary* _startCallbacks;
	NSMutableDictionary* _namesToScan;
	NSMutableDictionary* _connectingPeripherals;
	NSMutableDictionary* _discoveryPeripherals;
	NSMutableDictionary* _characteristicCallbacks;
	NSMutableDictionary* _valueChangeCallbacks;
	NSMutableDictionary* _writeCallbacks;
	NSMutableDictionary* _readCallbacks;
	CBCentralManager* _centralManager;
	NSObject*<OS_dispatch_queue> _centralManagerQueue;

}

@property (retain) NSMutableDictionary * startCallbacks;                          //@synthesize startCallbacks=_startCallbacks - In the implementation block
@property (retain) NSMutableDictionary * namesToScan;                             //@synthesize namesToScan=_namesToScan - In the implementation block
@property (retain) NSMutableDictionary * connectingPeripherals;                   //@synthesize connectingPeripherals=_connectingPeripherals - In the implementation block
@property (retain) NSMutableDictionary * discoveryPeripherals;                    //@synthesize discoveryPeripherals=_discoveryPeripherals - In the implementation block
@property (retain) NSMutableDictionary * characteristicCallbacks;                 //@synthesize characteristicCallbacks=_characteristicCallbacks - In the implementation block
@property (retain) NSMutableDictionary * valueChangeCallbacks;                    //@synthesize valueChangeCallbacks=_valueChangeCallbacks - In the implementation block
@property (retain) NSMutableDictionary * writeCallbacks;                          //@synthesize writeCallbacks=_writeCallbacks - In the implementation block
@property (retain) NSMutableDictionary * readCallbacks;                           //@synthesize readCallbacks=_readCallbacks - In the implementation block
@property (retain) CBCentralManager * centralManager;                             //@synthesize centralManager=_centralManager - In the implementation block
@property (retain) NSObject*<OS_dispatch_queue> centralManagerQueue;              //@synthesize centralManagerQueue=_centralManagerQueue - In the implementation block
@property (assign) BOOL poweredOn;                                                //@synthesize poweredOn=_poweredOn - In the implementation block
@property (nonatomic,readonly) BOOL isScanning; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)enableValueChangeNotification:(BOOL)arg1 forCharacteristic:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)writeData:(id)arg1 forCharacteristic:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)readValueForCharacteristic:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)discoverCharacteristicsForService:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)discoverServices:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)connectPeripheral:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)disconnectPeripheral:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)startTag:(int)arg1 completion:(/*^block*/id)arg2 ;
-(void)stopTag:(int)arg1 ;
-(BOOL)startScanningPeripheralNamed:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)stopScanningPeripheralNamed:(id)arg1 ;
-(void)setStartCallbacks:(NSMutableDictionary *)arg1 ;
-(void)setNamesToScan:(NSMutableDictionary *)arg1 ;
-(void)setConnectingPeripherals:(NSMutableDictionary *)arg1 ;
-(void)setDiscoveryPeripherals:(NSMutableDictionary *)arg1 ;
-(void)setCharacteristicCallbacks:(NSMutableDictionary *)arg1 ;
-(void)setValueChangeCallbacks:(NSMutableDictionary *)arg1 ;
-(void)setWriteCallbacks:(NSMutableDictionary *)arg1 ;
-(void)setReadCallbacks:(NSMutableDictionary *)arg1 ;
-(NSMutableDictionary *)startCallbacks;
-(void)setCentralManagerQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(NSObject*<OS_dispatch_queue>)centralManagerQueue;
-(void)setPoweredOn:(BOOL)arg1 ;
-(NSMutableDictionary *)namesToScan;
-(BOOL)poweredOn;
-(NSMutableDictionary *)connectingPeripherals;
-(NSMutableDictionary *)discoveryPeripherals;
-(NSMutableDictionary *)characteristicCallbacks;
-(NSMutableDictionary *)valueChangeCallbacks;
-(NSMutableDictionary *)readCallbacks;
-(NSMutableDictionary *)writeCallbacks;
-(id)init;
-(BOOL)isScanning;
-(CBCentralManager *)centralManager;
-(void)setCentralManager:(CBCentralManager *)arg1 ;
-(void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3 ;
-(void)peripheral:(id)arg1 didDiscoverServices:(id)arg2 ;
-(void)peripheral:(id)arg1 didDiscoverCharacteristicsForService:(id)arg2 error:(id)arg3 ;
-(void)peripheral:(id)arg1 didWriteValueForCharacteristic:(id)arg2 error:(id)arg3 ;
-(void)peripheral:(id)arg1 didUpdateNotificationStateForCharacteristic:(id)arg2 error:(id)arg3 ;
-(void)centralManagerDidUpdateState:(id)arg1 ;
-(void)centralManager:(id)arg1 didDiscoverPeripheral:(id)arg2 advertisementData:(id)arg3 RSSI:(id)arg4 ;
-(void)centralManager:(id)arg1 didConnectPeripheral:(id)arg2 ;
-(void)centralManager:(id)arg1 didFailToConnectPeripheral:(id)arg2 error:(id)arg3 ;
-(void)centralManager:(id)arg1 didDisconnectPeripheral:(id)arg2 error:(id)arg3 ;
@end

