/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface PlayerWrapper : NSObject
+(void)loadUserPhotoAsyncAndTriggerCallbackWhenNeeded:(id)arg1 withCondition:(BOOL)arg2 index:(int)arg3 totalSize:(int)arg4 ;
+(void)processUsers:(id)arg1 withCondition:(BOOL)arg2 friendCallback:(/*^block*/id)arg3 ;
+(void)loadUserIds:(id)arg1 withCondition:(BOOL)arg2 ;
+(void)processNonFriendUsersUsingNewAPI:(id)arg1 withFriends:(id)arg2 ;
+(void)loadFriends;
@end

