/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <pokemongo/pokemongo-Structs.h>
@class PLCrashReporterConfig, PLCrashMachExceptionServer, PLCrashMachExceptionPortSet, NSString;

@interface PLCrashReporter : NSObject {

	PLCrashReporterConfig* _config;
	BOOL _enabled;
	PLCrashMachExceptionServer* _machServer;
	PLCrashMachExceptionPortSet* _previousMachPorts;
	NSString* _applicationIdentifier;
	NSString* _applicationVersion;
	NSString* _applicationMarketingVersion;
	NSString* _crashReportDirectory;

}
+(id)sharedReporter;
+(void)initialize;
-(id)initWithBundle:(id)arg1 configuration:(id)arg2 ;
-(id)crashReportPath;
-(BOOL)populateCrashReportDirectoryAndReturnError:(id*)arg1 ;
-(int)mapToAsyncSymbolicationStrategy:(unsigned long long)arg1 ;
-(id)enableMachExceptionServerWithPreviousPortSet:(id*)arg1 callback:(/*function pointer*/void*)arg2 context:(void*)arg3 error:(id*)arg4 ;
-(id)crashReportDirectory;
-(id)queuedCrashReportDirectory;
-(id)initWithApplicationIdentifier:(id)arg1 appVersion:(id)arg2 appMarketingVersion:(id)arg3 configuration:(id)arg4 ;
-(void)dealloc;
-(void)setCrashCallbacks:(PLCrashReporterCallbacks*)arg1 ;
-(id)loadPendingCrashReportDataAndReturnError:(id*)arg1 ;
-(BOOL)purgePendingCrashReportAndReturnError:(id*)arg1 ;
-(BOOL)enableCrashReporterAndReturnError:(id*)arg1 ;
-(id)generateLiveReportWithThread:(unsigned)arg1 error:(id*)arg2 ;
-(id)generateLiveReportAndReturnError:(id*)arg1 ;
-(BOOL)hasPendingCrashReport;
-(id)loadPendingCrashReportData;
-(BOOL)purgePendingCrashReport;
-(BOOL)enableCrashReporter;
-(id)generateLiveReportWithThread:(unsigned)arg1 ;
-(id)generateLiveReport;
-(id)init;
-(id)initWithConfiguration:(id)arg1 ;
@end

