/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/pokemongo-Structs.h>
#import <libobjc.A.dylib/NSFastEnumeration.h>

@class NSSet;

@interface PLCrashMachExceptionPortSet : NSObject <NSFastEnumeration> {

	NSSet* _state_set;
	plcrash_mach_exception_port_set _asyncSafeRepresentation;

}

@property (nonatomic,readonly) NSSet * set;                                                          //@synthesize state_set=_state_set - In the implementation block
@property (nonatomic,readonly) plcrash_mach_exception_port_set asyncSafeRepresentation;              //@synthesize asyncSafeRepresentation=_asyncSafeRepresentation - In the implementation block
-(plcrash_mach_exception_port_set)asyncSafeRepresentation;
-(id)initWithAsyncSafeRepresentation:(plcrash_mach_exception_port_set)arg1 ;
-(unsigned long long)countByEnumeratingWithState:(SCD_Struct_Un12*)arg1 objects:(id*)arg2 count:(unsigned long long)arg3 ;
-(void)dealloc;
-(NSSet *)set;
-(id)initWithSet:(id)arg1 ;
@end

