/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface PurchasableItemDetails : NSObject {

	NSString* _itemId;
	NSString* _title;
	NSString* _itemDescription;
	NSString* _price;

}

@property (readonly) NSString * itemId;                       //@synthesize itemId=_itemId - In the implementation block
@property (readonly) NSString * title;                        //@synthesize title=_title - In the implementation block
@property (readonly) NSString * itemDescription;              //@synthesize itemDescription=_itemDescription - In the implementation block
@property (readonly) NSString * price;                        //@synthesize price=_price - In the implementation block
-(id)init:(id)arg1 title:(id)arg2 description:(id)arg3 price:(id)arg4 ;
-(NSString *)itemId;
-(NSString *)title;
-(NSString *)price;
-(NSString *)itemDescription;
@end

