/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/pokemongo-Structs.h>
#import <pokemongo/RenderPluginDelegate.h>

@class NSArray;

@interface RenderPluginArrayDelegate : RenderPluginDelegate {

	NSArray* delegateArray;

}

@property (nonatomic,retain) NSArray * delegateArray; 
-(void)mainDisplayInited:(UnityDisplaySurfaceBase*)arg1 ;
-(void)onFrameResolved;
-(void)onBeforeMainDisplaySurfaceRecreate:(RenderingSurfaceParamsRef)arg1 ;
-(void)onAfterMainDisplaySurfaceRecreate;
-(void)willTerminate:(id)arg1 ;
-(NSArray *)delegateArray;
-(void)setDelegateArray:(NSArray *)arg1 ;
-(void)willResignActive:(id)arg1 ;
-(void)didBecomeActive:(id)arg1 ;
-(void)didEnterBackground:(id)arg1 ;
-(void)willEnterForeground:(id)arg1 ;
@end

