/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <pokemongo/pokemongo-Structs.h>
@interface UnityPLCrashMachExceptionServer : NSObject {

	plcrash_exception_server_context* _serverContext;

}

@property (nonatomic,readonly) unsigned serverThread; 
-(id)initWithCallBack:(/*function pointer*/void*)arg1 context:(void*)arg2 error:(id*)arg3 ;
-(id)exceptionPortWithMask:(unsigned)arg1 error:(id*)arg2 ;
-(unsigned)copySendRightForServerAndReturningError:(id*)arg1 ;
-(unsigned)serverThread;
-(void)dealloc;
@end

