/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/ADInterstitialAdDelegate.h>
#import <pokemongo/UnityViewControllerListener.h>

@class ADInterstitialAd, UIViewController, NSString;

@interface UnityInterstitialAd : NSObject <ADInterstitialAdDelegate, UnityViewControllerListener> {

	ADInterstitialAd* _interstitial;
	UIViewController* _presentController;
	BOOL _autoReload;
	BOOL _didShowAd;

}

@property (nonatomic,copy,readonly) ADInterstitialAd * interstitial;              //@synthesize interstitial=_interstitial - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_unloadAD;
-(void)_loadAD;
-(void)reloadAD;
-(void)_handleReloadAD;
-(id)initWithController:(id)arg1 autoReload:(BOOL)arg2 ;
-(ADInterstitialAd *)interstitial;
-(void)show;
-(void)dealloc;
-(void)viewWillAppear:(id)arg1 ;
-(void)viewDidDisappear:(id)arg1 ;
-(void)interstitialAdDidUnload:(id)arg1 ;
-(void)interstitialAdDidLoad:(id)arg1 ;
-(void)interstitialAd:(id)arg1 didFailWithError:(id)arg2 ;
-(void)interstitialAdActionDidFinish:(id)arg1 ;
-(BOOL)interstitialAdActionShouldBegin:(id)arg1 willLeaveApplication:(BOOL)arg2 ;
@end

