/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface UnityPLCrashReportSignalInfo : NSObject {

	NSString* _name;
	NSString* _code;
	unsigned long long _address;

}

@property (nonatomic,readonly) NSString * name;                         //@synthesize name=_name - In the implementation block
@property (nonatomic,readonly) NSString * code;                         //@synthesize code=_code - In the implementation block
@property (nonatomic,readonly) unsigned long long address;              //@synthesize address=_address - In the implementation block
-(id)initWithSignalName:(id)arg1 code:(id)arg2 address:(unsigned long long)arg3 ;
-(unsigned long long)address;
-(void)dealloc;
-(NSString *)name;
-(NSString *)code;
@end

