/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface UnityPLCrashReportApplicationInfo : NSObject {

	NSString* _applicationIdentifier;
	NSString* _applicationVersion;

}

@property (nonatomic,readonly) NSString * applicationIdentifier;              //@synthesize applicationIdentifier=_applicationIdentifier - In the implementation block
@property (nonatomic,readonly) NSString * applicationVersion;                 //@synthesize applicationVersion=_applicationVersion - In the implementation block
-(id)initWithApplicationIdentifier:(id)arg1 applicationVersion:(id)arg2 ;
-(void)dealloc;
-(NSString *)applicationIdentifier;
-(NSString *)applicationVersion;
@end

