/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSDate;

@interface UnityPLCrashReportSystemInfo : NSObject {

	int _operatingSystem;
	NSString* _osVersion;
	NSString* _osBuild;
	int _architecture;
	NSDate* _timestamp;

}

@property (nonatomic,readonly) int operatingSystem;                            //@synthesize operatingSystem=_operatingSystem - In the implementation block
@property (nonatomic,readonly) NSString * operatingSystemVersion;              //@synthesize osVersion=_osVersion - In the implementation block
@property (nonatomic,readonly) NSString * operatingSystemBuild;                //@synthesize osBuild=_osBuild - In the implementation block
@property (nonatomic,readonly) int architecture;                               //@synthesize architecture=_architecture - In the implementation block
@property (nonatomic,readonly) NSDate * timestamp;                             //@synthesize timestamp=_timestamp - In the implementation block
-(id)initWithOperatingSystem:(int)arg1 operatingSystemVersion:(id)arg2 operatingSystemBuild:(id)arg3 architecture:(int)arg4 timestamp:(id)arg5 ;
-(id)initWithOperatingSystem:(int)arg1 operatingSystemVersion:(id)arg2 architecture:(int)arg3 timestamp:(id)arg4 ;
-(NSString *)operatingSystemBuild;
-(int)operatingSystem;
-(NSString *)operatingSystemVersion;
-(void)dealloc;
-(NSDate *)timestamp;
-(int)architecture;
@end

