/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSObject, NSOperationQueue, NSPredicate;

@interface UpsightObserverInfo : NSObject {

	NSString* _selector;
	NSObject* _observer;
	NSOperationQueue* _queue;
	NSPredicate* _predicate;

}

@property (nonatomic,copy) NSString * selector;                       //@synthesize selector=_selector - In the implementation block
@property (assign,nonatomic,__weak) NSObject * observer;              //@synthesize observer=_observer - In the implementation block
@property (nonatomic,retain) NSOperationQueue * queue;                //@synthesize queue=_queue - In the implementation block
@property (nonatomic,retain) NSPredicate * predicate;                 //@synthesize predicate=_predicate - In the implementation block
-(NSOperationQueue *)queue;
-(void)setQueue:(NSOperationQueue *)arg1 ;
-(void)setSelector:(NSString *)arg1 ;
-(NSString *)selector;
-(void)setPredicate:(NSPredicate *)arg1 ;
-(NSPredicate *)predicate;
-(NSObject *)observer;
-(void)setObserver:(NSObject *)arg1 ;
@end

