/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSNumber, UpsightInternalObject;

@interface UpsightStorableObject : NSObject {

	BOOL _readOnly;
	NSString* _type;
	NSNumber* _version;
	NSString* _ID;
	UpsightInternalObject* _internalObject;
	NSNumber* _storeCount;

}

@property (nonatomic,copy) NSString * type;                                       //@synthesize type=_type - In the implementation block
@property (nonatomic,readonly) NSNumber * version;                                //@synthesize version=_version - In the implementation block
@property (nonatomic,retain) NSString * ID;                                       //@synthesize ID=_ID - In the implementation block
@property (nonatomic,retain) UpsightInternalObject * internalObject;              //@synthesize internalObject=_internalObject - In the implementation block
@property (assign,nonatomic) BOOL readOnly;                                       //@synthesize readOnly=_readOnly - In the implementation block
@property (nonatomic,retain) NSNumber * storeCount;                               //@synthesize storeCount=_storeCount - In the implementation block
-(id)initWithType:(id)arg1 version:(id)arg2 ID:(id)arg3 ;
-(id)dictionaryRepresentation:(id*)arg1 ;
-(UpsightInternalObject *)internalObject;
-(void)setInternalObject:(UpsightInternalObject *)arg1 ;
-(NSNumber *)storeCount;
-(void)setStoreCount:(NSNumber *)arg1 ;
-(void)setReadOnly:(BOOL)arg1 ;
-(id)init;
-(void)setType:(NSString *)arg1 ;
-(NSString *)type;
-(id)initWithType:(id)arg1 ;
-(BOOL)readOnly;
-(NSNumber *)version;
-(NSString *)ID;
-(void)setID:(NSString *)arg1 ;
-(id)initWithDictionaryRepresentation:(id)arg1 ;
-(id)propertyNames;
@end

