/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol UpsightDataStoreInterface <NSObject>
@required
-(void)addObserver:(id)arg1 selector:(SEL)arg2 type:(id)arg3 queue:(id)arg4 predicate:(id)arg5;
-(void)removeObserver:(id)arg1 type:(id)arg2;
-(void)remove:(id)arg1 completion:(/*^block*/id)arg2;
-(id)queryObjects:(id)arg1 predicate:(id)arg2;
-(void)store:(id)arg1 completion:(/*^block*/id)arg2;
-(void)addObserver:(id)arg1 selector:(SEL)arg2 type:(id)arg3 queue:(id)arg4;
-(void)removeObserver:(id)arg1 type:(id)arg2 predicate:(id)arg3;
-(void)addObserver:(id)arg1 selector:(SEL)arg2 type:(id)arg3;
-(void)addDefaultObserver:(id)arg1 selector:(SEL)arg2;
-(void)removeDefaultObserver:(id)arg1;
-(void)removeObjects:(id)arg1 completion:(/*^block*/id)arg2;

@end

