/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, UpsightDataStore;

@interface UpsightLogger : NSObject {

	NSString* _name;
	UpsightDataStore* _store;

}

@property (nonatomic,copy) NSString * name;                         //@synthesize name=_name - In the implementation block
@property (nonatomic,retain) UpsightDataStore * store;              //@synthesize store=_store - In the implementation block
+(void)initialize;
+(long long)defaultLogLevel;
+(id)loggerForName:(id)arg1 ;
+(void)setDefaultLogLevel:(long long)arg1 ;
-(id)initWithName:(id)arg1 store:(id)arg2 ;
-(void)observeLogDataStored:(id)arg1 action:(unsigned long long)arg2 ;
-(void)logDataWithLevel:(long long)arg1 fileName:(id)arg2 line:(long long)arg3 function:(id)arg4 message:(id)arg5 ;
-(UpsightDataStore *)store;
-(void)setStore:(UpsightDataStore *)arg1 ;
-(void)dealloc;
-(void)setName:(NSString *)arg1 ;
-(NSString *)name;
-(void)logMessage:(id)arg1 ;
@end

