/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSDictionary, USActionMap;


@protocol USAction <NSObject>
@property (nonatomic,readonly) NSDictionary * parameters; 
@property (nonatomic,__weak,readonly) USActionMap * map; 
@property (nonatomic,copy,readonly) id handler; 
@required
+(id)type;
-(void)executeWithCompletionBlock:(/*^block*/id)arg1;
-(id)handler;
-(NSDictionary *)parameters;
-(USActionMap *)map;

@end

