/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/USConfigurationBase.h>

@class NSString;

@interface USAttributeSetFilterConfiguration : USConfigurationBase {

	NSString* _filter;
	NSString* _attributeSet;

}

@property (nonatomic,retain) NSString * filter;                    //@synthesize filter=_filter - In the implementation block
@property (nonatomic,retain) NSString * attributeSet;              //@synthesize attributeSet=_attributeSet - In the implementation block
+(BOOL)isValidConfigurationDictionary:(id)arg1 ;
+(id)requiredKeys;
-(NSString *)filter;
-(void)setFilter:(NSString *)arg1 ;
-(void)setAttributeSet:(NSString *)arg1 ;
-(NSString *)attributeSet;
-(id)initWithConfigurationDictionary:(id)arg1 ;
@end

