/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:16 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol USBillboardDelegate <NSObject>
@optional
-(void)billboardWillAppear:(id)arg1;
-(void)billboardDidAppear:(id)arg1;
-(void)billboardWillDismiss:(id)arg1;
-(void)billboardDidDismiss:(id)arg1;
-(void)billboard:(id)arg1 didReceiveReward:(id)arg2;
-(void)billboard:(id)arg1 didReceivePurchase:(id)arg2;

@required
-(id)presentingViewControllerForBillboard:(id)arg1;

@end

