/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/UpsightStorableObject.h>

@class NSString, NSDictionary, NSNumber;

@interface USConfiguration : UpsightStorableObject {

	NSString* _configurationType;
	NSDictionary* _configurationDictionary;
	NSNumber* _sessionNumber;

}

@property (nonatomic,readonly) NSString * configurationType;                        //@synthesize configurationType=_configurationType - In the implementation block
@property (nonatomic,readonly) NSDictionary * configurationDictionary;              //@synthesize configurationDictionary=_configurationDictionary - In the implementation block
@property (nonatomic,readonly) NSNumber * sessionNumber;                            //@synthesize sessionNumber=_sessionNumber - In the implementation block
-(id)initWithType:(id)arg1 version:(id)arg2 ID:(id)arg3 ;
-(id)initWithConfigurationType:(id)arg1 configurationDictionary:(id)arg2 sessionNumber:(id)arg3 ;
-(NSString *)configurationType;
-(id)init;
-(NSNumber *)sessionNumber;
-(NSDictionary *)configurationDictionary;
@end

