/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/USBaseAction.h>

@class NSDictionary, NSString;

@interface USConditionalAction : USBaseAction {

	NSDictionary* _conditionParameters;
	NSString* _thenTrigger;
	NSString* _elseTrigger;

}

@property (nonatomic,readonly) NSDictionary * conditionParameters;              //@synthesize conditionParameters=_conditionParameters - In the implementation block
@property (nonatomic,readonly) NSString * thenTrigger;                          //@synthesize thenTrigger=_thenTrigger - In the implementation block
@property (nonatomic,readonly) NSString * elseTrigger;                          //@synthesize elseTrigger=_elseTrigger - In the implementation block
-(id)initWithParameters:(id)arg1 map:(id)arg2 handler:(/*^block*/id)arg3 ;
-(NSString *)thenTrigger;
-(NSString *)elseTrigger;
-(NSDictionary *)conditionParameters;
@end

