/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol USContentUnitViewControllerCacheDelegate;
@class NSMutableDictionary;

@interface USContentUnitViewControllerCache : NSObject {

	NSMutableDictionary* _actionMapIDToControllerMap;
	id<USContentUnitViewControllerCacheDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<USContentUnitViewControllerCacheDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) NSMutableDictionary * actionMapIDToControllerMap;                        //@synthesize actionMapIDToControllerMap=_actionMapIDToControllerMap - In the implementation block
-(id)anyControllerForScope:(id)arg1 ;
-(id)controllerForActionMapID:(id)arg1 ;
-(NSMutableDictionary *)actionMapIDToControllerMap;
-(void)addController:(id)arg1 ;
-(void)removeController:(id)arg1 ;
-(void)setDelegate:(id<USContentUnitViewControllerCacheDelegate>)arg1 ;
-(id<USContentUnitViewControllerCacheDelegate>)delegate;
@end

