/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/UpsightDefaultsImpl.h>

@protocol UpsightDataStoreInterface;
@class NSMutableDictionary, NSString;

@interface USDataStoreBasedDefaultsImpl : NSObject <UpsightDefaultsImpl> {

	NSMutableDictionary* _defaultsMap;
	id<UpsightDataStoreInterface> _dataStore;

}

@property (nonatomic,readonly) id<UpsightDataStoreInterface> dataStore;              //@synthesize dataStore=_dataStore - In the implementation block
@property (readonly) NSMutableDictionary * defaultsMap;                              //@synthesize defaultsMap=_defaultsMap - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(NSMutableDictionary *)defaultsMap;
-(void)removeDefaultForKey:(id)arg1 ;
-(void)setDefault:(id)arg1 forKey:(id)arg2 ;
-(void)removeAllDefaults;
-(id)init;
-(id)initWithDataStore:(id)arg1 ;
-(id<UpsightDataStoreInterface>)dataStore;
-(id)defaultForKey:(id)arg1 ;
@end

