/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/USEvent.h>

@class NSString;

@interface USDataCollectionEvent : USEvent

@property (nonatomic,copy,readonly) NSString * format; 
@property (nonatomic,copy,readonly) NSString * dataBundle; 
@property (nonatomic,copy,readonly) NSString * streamID; 
-(id)initWithType:(id)arg1 parameters:(id)arg2 ;
-(id)initWithParameters:(id)arg1 format:(id)arg2 dataBundle:(id)arg3 streamID:(id)arg4 ;
-(NSString *)format;
-(NSString *)streamID;
-(NSString *)dataBundle;
@end

