/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class USQueueConfiguration, NSString;


@protocol USDeliveryQueueInterface
@property (nonatomic,readonly) USQueueConfiguration * queueConfiguration; 
@property (nonatomic,readonly) NSString * name; 
@property (assign,nonatomic,__weak) id<USDeliveryQueueDelegate> delegate; 
@required
-(USQueueConfiguration *)queueConfiguration;
-(void)enqueuePacket:(id)arg1;
-(void)setDelegate:(id)arg1;
-(id<USDeliveryQueueDelegate>)delegate;
-(NSString *)name;
-(void)drain;

@end

