/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/USConfigurationBase.h>

@class NSArray;

@interface USDispatcherConfiguration : USConfigurationBase {

	NSArray* _queues;
	NSArray* _routeFilters;
	NSArray* _attributeSets;
	NSArray* _attributeFilters;

}

@property (nonatomic,retain) NSArray * queues;                        //@synthesize queues=_queues - In the implementation block
@property (nonatomic,retain) NSArray * routeFilters;                  //@synthesize routeFilters=_routeFilters - In the implementation block
@property (nonatomic,retain) NSArray * attributeSets;                 //@synthesize attributeSets=_attributeSets - In the implementation block
@property (nonatomic,retain) NSArray * attributeFilters;              //@synthesize attributeFilters=_attributeFilters - In the implementation block
+(BOOL)isValidConfigurationDictionary:(id)arg1 ;
+(BOOL)isValidArrayOfConfigurationDictionaries:(id)arg1 forClass:(Class)arg2 ;
+(id)loadConfigurationDictionaryFromPlist;
+(id)defaultConfigurationDictionary;
+(id)defaultConfiguration;
-(NSArray *)routeFilters;
-(NSArray *)queues;
-(void)setAttributeSets:(NSArray *)arg1 ;
-(void)setQueues:(NSArray *)arg1 ;
-(NSArray *)attributeFilters;
-(void)setRouteFilters:(NSArray *)arg1 ;
-(void)setAttributeFilters:(NSArray *)arg1 ;
-(id)initWithConfigurationDictionary:(id)arg1 ;
-(NSArray *)attributeSets;
@end

