/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableArray, NSArray;

@interface USEventBatch : NSObject {

	NSMutableArray* _itemsArray;
	unsigned long long _batchSize;

}

@property (getter=isFull,nonatomic,readonly) BOOL full; 
@property (nonatomic,readonly) NSArray * items; 
@property (nonatomic,readonly) unsigned long long batchSize;              //@synthesize batchSize=_batchSize - In the implementation block
@property (nonatomic,readonly) NSMutableArray * itemsArray;               //@synthesize itemsArray=_itemsArray - In the implementation block
-(id)initWithBatchSize:(unsigned long long)arg1 ;
-(id)dictionaryRepresentationWithBatchParameters:(id)arg1 ;
-(NSMutableArray *)itemsArray;
-(void)addEventsFromArray:(id)arg1 ;
-(void)addEvent:(id)arg1 ;
-(BOOL)isFull;
-(unsigned long long)batchSize;
-(NSArray *)items;
@end

