/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSCoding.h>

@class NSString, USUpsightDataFilter, NSDictionary;

@interface USEventDataAssociation : NSObject <NSCoding> {

	NSString* _eventType;
	USUpsightDataFilter* _upsightDataFilter;
	NSDictionary* _upsightData;

}

@property (nonatomic,readonly) NSString * eventType;                                 //@synthesize eventType=_eventType - In the implementation block
@property (nonatomic,readonly) USUpsightDataFilter * upsightDataFilter;              //@synthesize upsightDataFilter=_upsightDataFilter - In the implementation block
@property (nonatomic,readonly) NSDictionary * upsightData;                           //@synthesize upsightData=_upsightData - In the implementation block
+(id)associationWithEventType:(id)arg1 upsightDataFilter:(id)arg2 upsightData:(id)arg3 ;
-(NSDictionary *)upsightData;
-(id)initWithEventType:(id)arg1 upsightDataFilter:(id)arg2 upsightData:(id)arg3 ;
-(USUpsightDataFilter *)upsightDataFilter;
-(BOOL)isEqualToAssociation:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(NSString *)eventType;
@end

