/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol UpsightDataStoreInterface;
@class NSMutableDictionary;

@interface USEventDataAssociationMap : NSObject {

	NSMutableDictionary* _typeToAssociationsMap;
	id<UpsightDataStoreInterface> _dataStore;
	double _expirationInterval;

}

@property (nonatomic,readonly) id<UpsightDataStoreInterface> dataStore;                  //@synthesize dataStore=_dataStore - In the implementation block
@property (nonatomic,readonly) NSMutableDictionary * typeToAssociationsMap;              //@synthesize typeToAssociationsMap=_typeToAssociationsMap - In the implementation block
@property (nonatomic,readonly) double expirationInterval;                                //@synthesize expirationInterval=_expirationInterval - In the implementation block
-(id)initWithDataStore:(id)arg1 expirationInterval:(double)arg2 ;
-(id)associationsForEventType:(id)arg1 ;
-(void)removeAssociation:(id)arg1 ;
-(void)addAssociation:(id)arg1 ;
-(NSMutableDictionary *)typeToAssociationsMap;
-(void)cacheStorables:(id)arg1 ;
-(void)removeCachedStorables:(id)arg1 ;
-(void)filterStorables:(id)arg1 expired:(id*)arg2 valid:(id*)arg3 ;
-(void)loadAndCacheAssociationStorables;
-(BOOL)isStorableExpired:(id)arg1 ;
-(id)init;
-(id<UpsightDataStoreInterface>)dataStore;
-(double)expirationInterval;
@end

