/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol USEventRouterDelegate <NSObject>
@required
-(void)eventRouterDidDrain:(id)arg1;
-(void)eventRouter:(id)arg1 didDeliverItems:(id)arg2 response:(id)arg3;
-(void)eventRouter:(id)arg1 didFailWithError:(id)arg2 items:(id)arg3;

@end

