/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/UpsightStorableObject.h>

@class USEvent, NSError;

@interface USEventResponse : UpsightStorableObject {

	USEvent* _event;
	NSError* _error;

}

@property (nonatomic,readonly) USEvent * event;              //@synthesize event=_event - In the implementation block
@property (nonatomic,readonly) NSError * error;              //@synthesize error=_error - In the implementation block
-(id)initWithType:(id)arg1 version:(id)arg2 ID:(id)arg3 ;
-(id)initWithEvent:(id)arg1 error:(id)arg2 ;
-(NSError *)error;
-(id)init;
-(USEvent *)event;
@end

