/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <pokemongo/pokemongo-Structs.h>
@interface USEventFactory : NSObject
+(id)analyticsEventWithName:(id)arg1 pubData:(id)arg2 ;
+(id)monetizationEventWithInfo:(id)arg1 pubData:(id)arg2 ;
+(id)inAppPurchaseEventWithIAPInfo:(id)arg1 pubData:(id)arg2 ;
+(id)milestoneEventForScope:(id)arg1 pubData:(id)arg2 ;
+(id)pushUnregistrationEventWithPubData:(id)arg1 ;
+(id)pushRegistrationEventWithToken:(id)arg1 pubData:(id)arg2 ;
+(id)unrenderedContentEventWithContentID:(id)arg1 campaignID:(id)arg2 scope:(id)arg3 pubData:(id)arg4 ;
+(id)pushReceivedEventWithMessageID:(id)arg1 campaignID:(id)arg2 pubData:(id)arg3 ;
+(id)configurationRequestWithPubData:(id)arg1 ;
+(id)dataCollectionEventWitDataBundle:(id)arg1 streamID:(id)arg2 pubData:(id)arg3 ;
+(id)dynamicEventWithEventDictionary:(id)arg1 ;
+(id)UXMEnumerateEventWithUXMSchema:(id)arg1 pubData:(id)arg2 ;
+(id)installEventWithPubData:(id)arg1 ;
+(id)sessionStartEventWithPubData:(id)arg1 ;
+(id)sessionPauseEventWithPubData:(id)arg1 ;
+(id)sessionResumeEventWithPubData:(id)arg1 ;
+(id)sharedFactory;
-(id)eventParametersWithAttributeSetName:(id)arg1 pubData:(id)arg2 ;
-(void)extendEventWithAssociatedData:(id)arg1 ;
-(id)buildEventWithInitializer:(/*^block*/id)arg1 attributeSetName:(id)arg2 pubData:(id)arg3 ;
-(id)copyWithZone:(NSZone*)arg1 ;
@end

