/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class USActionMap, NSString, NSTimer;

@interface USExecuteTriggerTask : NSObject {

	BOOL _canceled;
	USActionMap* _map;
	double _timeout;
	NSString* _timeoutTrigger;
	NSString* _cancelTrigger;
	NSTimer* _timer;

}

@property (nonatomic,readonly) USActionMap * map;                          //@synthesize map=_map - In the implementation block
@property (nonatomic,readonly) double timeout;                             //@synthesize timeout=_timeout - In the implementation block
@property (nonatomic,readonly) NSString * timeoutTrigger;                  //@synthesize timeoutTrigger=_timeoutTrigger - In the implementation block
@property (nonatomic,readonly) NSString * cancelTrigger;                   //@synthesize cancelTrigger=_cancelTrigger - In the implementation block
@property (nonatomic,retain) NSTimer * timer;                              //@synthesize timer=_timer - In the implementation block
@property (assign,getter=isCanceled,nonatomic) BOOL canceled;              //@synthesize canceled=_canceled - In the implementation block
-(id)initWithActionMap:(id)arg1 timeout:(double)arg2 timeoutTrigger:(id)arg3 cancelTrigger:(id)arg4 ;
-(void)onTimeoutDidFire:(id)arg1 ;
-(NSString *)timeoutTrigger;
-(double)timeout;
-(void)cancel;
-(id)init;
-(void)setTimer:(NSTimer *)arg1 ;
-(NSTimer *)timer;
-(void)setCanceled:(BOOL)arg1 ;
-(BOOL)isCanceled;
-(USActionMap *)map;
-(NSString *)cancelTrigger;
@end

