/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/USPurchaseInfo.h>

@class NSString, NSDictionary;

@interface USInAppPurchaseInfo : USPurchaseInfo {

	NSString* _transactionIdentifier;
	NSDictionary* _IAPBundle;

}

@property (nonatomic,readonly) unsigned long long resolution; 
@property (nonatomic,readonly) NSString * product; 
@property (nonatomic,readonly) unsigned long long quantity; 
@property (nonatomic,readonly) NSString * transactionIdentifier;                     //@synthesize transactionIdentifier=_transactionIdentifier - In the implementation block
@property (nonatomic,retain) NSString * currency; 
@property (assign,nonatomic) float price; 
@property (assign,nonatomic) float totalPrice; 
@property (nonatomic,readonly) NSDictionary * dictionaryRepresentation; 
@property (nonatomic,retain) NSDictionary * IAPBundle;                               //@synthesize IAPBundle=_IAPBundle - In the implementation block
+(id)IAPInfoWithResolution:(unsigned long long)arg1 currency:(id)arg2 quantity:(unsigned long long)arg3 product:(id)arg4 price:(float)arg5 transactionIdentifier:(id)arg6 ;
-(id)initWithResolution:(unsigned long long)arg1 totalPrice:(float)arg2 currency:(id)arg3 quantity:(unsigned long long)arg4 product:(id)arg5 price:(float)arg6 ;
-(id)initWithResolution:(unsigned long long)arg1 currency:(id)arg2 quantity:(unsigned long long)arg3 product:(id)arg4 price:(float)arg5 transactionIdentifier:(id)arg6 ;
-(NSDictionary *)IAPBundle;
-(void)setIAPBundle:(NSDictionary *)arg1 ;
-(NSString *)transactionIdentifier;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(NSDictionary *)dictionaryRepresentation;
-(id)initWithDictionaryRepresentation:(id)arg1 ;
@end

