/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/USDataBundle.h>

@class NSString, NSDictionary;

@interface USJSONDataBundle : NSObject <USDataBundle> {

	NSDictionary* _dataBundleDictionary;

}

@property (nonatomic,readonly) NSDictionary * dataBundleDictionary;              //@synthesize dataBundleDictionary=_dataBundleDictionary - In the implementation block
@property (nonatomic,readonly) NSString * formatString; 
@property (nonatomic,readonly) NSString * dataString; 
-(id)initWithDataBundleDictionary:(id)arg1 ;
-(NSString *)dataString;
-(NSDictionary *)dataBundleDictionary;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)init;
-(NSString *)formatString;
@end

