/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface USManagedVariable : NSObject {

	NSString* _tag;
	id _value;

}

@property (nonatomic,retain) NSString * tag;              //@synthesize tag=_tag - In the implementation block
@property (nonatomic,retain) id value;                    //@synthesize value=_value - In the implementation block
+(id)managedIntegerWithTag:(id)arg1 ;
+(id)managedStringWithTag:(id)arg1 ;
+(id)managedFloatWithTag:(id)arg1 ;
+(id)managedBooleanWithTag:(id)arg1 ;
+(id)keyPathsForValuesAffectingValueForKey:(id)arg1 ;
-(id)init;
-(long long)integerValue;
-(BOOL)boolValue;
-(id)value;
-(void)setValue:(id)arg1 ;
-(float)floatValue;
-(NSString *)tag;
-(void)setTag:(NSString *)arg1 ;
-(id)stringValue;
-(id)initWithTag:(id)arg1 value:(id)arg2 ;
@end

