/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSNumber;

@interface USMutableNumber : NSObject {

	NSNumber* _numberValue;

}

@property (assign,nonatomic) long long integerValue; 
@property (nonatomic,retain) NSNumber * numberValue;              //@synthesize numberValue=_numberValue - In the implementation block
-(void)setNumberValue:(NSNumber *)arg1 ;
-(id)init;
-(long long)integerValue;
-(id)initWithInteger:(unsigned long long)arg1 ;
-(NSNumber *)numberValue;
-(void)setIntegerValue:(long long)arg1 ;
@end

