/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <pokemongo/pokemongo-Structs.h>
@class NSString, NSDateFormatter, NSNumber;

@interface USParametersProvider : NSObject {

	NSString* _bundleID;
	NSString* _bundleVersion;
	NSString* _token;
	NSString* _deviceID;
	NSString* _OSVersion;
	NSString* _deviceType;
	NSDateFormatter* _timezoneDateFormatter;

}

@property (nonatomic,readonly) NSString * bundleID;                                                                    //@synthesize bundleID=_bundleID - In the implementation block
@property (nonatomic,readonly) NSString * bundleVersion;                                                               //@synthesize bundleVersion=_bundleVersion - In the implementation block
@property (nonatomic,readonly) NSString * token;                                                                       //@synthesize token=_token - In the implementation block
@property (nonatomic,readonly) NSString * carrierString; 
@property (nonatomic,readonly) NSString * deviceID;                                                                    //@synthesize deviceID=_deviceID - In the implementation block
@property (nonatomic,readonly) NSString * OSName; 
@property (nonatomic,readonly) NSString * OSVersion;                                                                   //@synthesize OSVersion=_OSVersion - In the implementation block
@property (nonatomic,readonly) NSString * deviceType;                                                                  //@synthesize deviceType=_deviceType - In the implementation block
@property (nonatomic,readonly) NSString * manufacturer; 
@property (getter=isJailbroken,nonatomic,readonly) NSNumber * jailbroken; 
@property (getter=isAdvertisingTrackingLimited,nonatomic,readonly) NSNumber * advertisingTrackingLimited; 
@property (nonatomic,readonly) NSNumber * screenHeight; 
@property (nonatomic,readonly) NSNumber * screenWidth; 
@property (nonatomic,readonly) NSNumber * screenScale; 
@property (nonatomic,readonly) NSString * SDKVersion; 
@property (nonatomic,readonly) NSString * SDKBuild; 
@property (nonatomic,readonly) NSString * SDKPluginVersion; 
@property (nonatomic,readonly) NSString * idfvString; 
@property (nonatomic,readonly) NSString * idfaString; 
@property (nonatomic,readonly) NSString * localeIdentifier; 
@property (nonatomic,readonly) NSString * networkReachabilityStatusString; 
@property (nonatomic,readonly) unsigned long long networkReachabilityStatus; 
@property (nonatomic,readonly) NSNumber * requestTimestamp; 
@property (nonatomic,readonly) NSString * SID; 
@property (getter=isOptOut,nonatomic,readonly) NSNumber * optOut; 
@property (nonatomic,readonly) NSString * locationTimezone; 
@property (nonatomic,readonly) NSString * locationLatitude; 
@property (nonatomic,readonly) NSString * locationLongitude; 
@property (nonatomic,readonly) NSNumber * locationHeight; 
@property (nonatomic,readonly) NSString * UXMBundleID; 
@property (nonatomic,readonly) NSString * UXMBundleHash; 
@property (nonatomic,readonly) NSString * UXMSchemaHash; 
@property (nonatomic,readonly) NSDateFormatter * timezoneDateFormatter;                                                //@synthesize timezoneDateFormatter=_timezoneDateFormatter - In the implementation block
+(id)sharedProvider;
-(NSString *)SID;
-(NSString *)SDKVersion;
-(id)isJailbroken;
-(id)isAdvertisingTrackingLimited;
-(id)isOptOut;
-(NSNumber *)requestTimestamp;
-(NSString *)carrierString;
-(NSString *)networkReachabilityStatusString;
-(NSString *)OSName;
-(NSString *)SDKBuild;
-(NSString *)SDKPluginVersion;
-(NSString *)locationTimezone;
-(NSString *)UXMBundleID;
-(NSString *)UXMBundleHash;
-(NSString *)UXMSchemaHash;
-(NSString *)idfvString;
-(NSString *)idfaString;
-(id)performBlockSyncOnMainThread:(/*^block*/id)arg1 ;
-(unsigned long long)networkReachabilityStatus;
-(BOOL)isLocalWiFiAvailable;
-(BOOL)isLANAvailable;
-(BOOL)isInterfaceAvailableWithName:(id)arg1 ;
-(NSDateFormatter *)timezoneDateFormatter;
-(NSNumber *)locationHeight;
-(NSString *)bundleID;
-(NSString *)locationLatitude;
-(NSString *)locationLongitude;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSString *)localeIdentifier;
-(NSNumber *)screenScale;
-(NSString *)token;
-(NSString *)bundleVersion;
-(NSString *)manufacturer;
-(id)currentLocation;
-(NSString *)deviceID;
-(NSString *)OSVersion;
-(NSNumber *)screenHeight;
-(NSNumber *)screenWidth;
-(NSString *)deviceType;
@end

