/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/USEvent.h>

@class NSNumber;

@interface USPushReceivedEvent : USEvent

@property (nonatomic,readonly) NSNumber * messageID; 
@property (nonatomic,readonly) NSNumber * campaignID; 
+(id)eventWithParameters:(id)arg1 messageID:(id)arg2 campaignID:(id)arg3 ;
-(id)initWithParameters:(id)arg1 messageID:(id)arg2 campaignID:(id)arg3 ;
-(id)initWithType:(id)arg1 parameters:(id)arg2 ;
-(NSNumber *)campaignID;
-(NSNumber *)messageID;
@end

