/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol USAnalyticsInterface, USBillboard, UpsightDataStoreInterface;
@interface USPush : NSObject {

	id<USAnalyticsInterface> _analytics;
	id<USBillboard> _billboard;
	id<UpsightDataStoreInterface> _dataStore;

}

@property (nonatomic,retain) id<UpsightDataStoreInterface> dataStore;              //@synthesize dataStore=_dataStore - In the implementation block
@property (nonatomic,readonly) id<USAnalyticsInterface> analytics;                 //@synthesize analytics=_analytics - In the implementation block
@property (nonatomic,readonly) id<USBillboard> billboard;                          //@synthesize billboard=_billboard - In the implementation block
+(void)registerForPushNotifications;
+(void)unregisterForPushNotifications;
+(void)registerPushToken:(id)arg1 ;
+(id)pushBillboard;
+(void)handleRemoteNotificationWithUserInfo:(id)arg1 ;
+(void)didRegisterUserNotificationSettings:(id)arg1 ;
+(id)sharedPushInstance;
+(void)extractMessageID:(id*)arg1 campaignID:(id*)arg2 userInfo:(id)arg3 ;
+(void)initialize;
-(id<USAnalyticsInterface>)analytics;
-(id<USBillboard>)billboard;
-(id)init;
-(id)initWithDataStore:(id)arg1 ;
-(void)setDataStore:(id<UpsightDataStoreInterface>)arg1 ;
-(id<UpsightDataStoreInterface>)dataStore;
@end

