/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/USReward.h>

@class NSString, NSData;

@interface USRewardImpl : NSObject <USReward> {

	NSString* _productIdentifier;
	unsigned long long _quantity;
	NSData* _signatureData;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) NSString * productIdentifier;              //@synthesize productIdentifier=_productIdentifier - In the implementation block
@property (nonatomic,readonly) unsigned long long quantity;               //@synthesize quantity=_quantity - In the implementation block
@property (nonatomic,readonly) NSData * signatureData;                    //@synthesize signatureData=_signatureData - In the implementation block
-(NSData *)signatureData;
-(NSString *)productIdentifier;
-(id)init;
-(id)initWithDictionary:(id)arg1 ;
-(unsigned long long)quantity;
@end

