/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface USRetryInfo : NSObject {

	unsigned long long _counter;

}

@property (assign,nonatomic) unsigned long long counter;              //@synthesize counter=_counter - In the implementation block
-(unsigned long long)counter;
-(void)setCounter:(unsigned long long)arg1 ;
@end

