/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <pokemongo/pokemongo-Structs.h>
@class NSString;

@interface USRSASigningHelper : NSObject {

	SecKeyRef _publicKeyReference;
	SecKeyRef _privateKeyReference;
	NSString* _publicKey;
	NSString* _privateKey;

}

@property (readonly) SecKeyRef publicKeyReference;               //@synthesize publicKeyReference=_publicKeyReference - In the implementation block
@property (readonly) SecKeyRef privateKeyReference;              //@synthesize privateKeyReference=_privateKeyReference - In the implementation block
@property (nonatomic,retain) NSString * publicKey;               //@synthesize publicKey=_publicKey - In the implementation block
@property (nonatomic,retain) NSString * privateKey;              //@synthesize privateKey=_privateKey - In the implementation block
-(id)initWithPublicKey:(id)arg1 privateKey:(id)arg2 ;
-(BOOL)verifySignature:(id)arg1 forMessage:(id)arg2 ;
-(id)stripPublicKeyHeader:(id)arg1 ;
-(SecKeyRef)keychainItemWithKey:(id)arg1 keyType:(void*)arg2 withTag:(id)arg3 ;
-(SecKeyRef)publicKeyReference;
-(SecKeyRef)privateKeyReference;
-(id)signatureForMessage:(id)arg1 ;
-(void)dealloc;
-(void)setPublicKey:(NSString *)arg1 ;
-(NSString *)publicKey;
-(void)setPrivateKey:(NSString *)arg1 ;
-(NSString *)privateKey;
@end

