/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface USStateDefinition : NSObject {

	/*^block*/id _enterBlock;
	/*^block*/id _executeBlock;
	/*^block*/id _exitBlock;

}

@property (nonatomic,copy) id enterBlock;                //@synthesize enterBlock=_enterBlock - In the implementation block
@property (nonatomic,copy) id executeBlock;              //@synthesize executeBlock=_executeBlock - In the implementation block
@property (nonatomic,copy) id exitBlock;                 //@synthesize exitBlock=_exitBlock - In the implementation block
-(id)enterBlock;
-(void)setEnterBlock:(id)arg1 ;
-(void)setExecuteBlock:(id)arg1 ;
-(id)exitBlock;
-(void)setExitBlock:(id)arg1 ;
-(id)executeBlock;
@end

