/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/USConditionalAction.h>

@class NSString;

@interface USTriggerIfContentAvailableAction : USConditionalAction {

	NSString* _ID;
	double _timeout;

}

@property (nonatomic,readonly) NSString * ID;               //@synthesize ID=_ID - In the implementation block
@property (nonatomic,readonly) double timeout;              //@synthesize timeout=_timeout - In the implementation block
+(id)type;
-(id)initWithParameters:(id)arg1 map:(id)arg2 handler:(/*^block*/id)arg3 ;
-(double)timeout;
-(NSString *)ID;
@end

