/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSURLConnection, NSURL;

@interface USURLLoaderItem : NSObject {

	NSURLConnection* _connection;
	NSURL* _resultingURL;
	unsigned long long _numberOfRedirects;

}

@property (nonatomic,retain) NSURLConnection * connection;                      //@synthesize connection=_connection - In the implementation block
@property (nonatomic,retain) NSURL * resultingURL;                              //@synthesize resultingURL=_resultingURL - In the implementation block
@property (assign,nonatomic) unsigned long long numberOfRedirects;              //@synthesize numberOfRedirects=_numberOfRedirects - In the implementation block
-(NSURL *)resultingURL;
-(void)setResultingURL:(NSURL *)arg1 ;
-(unsigned long long)numberOfRedirects;
-(void)setNumberOfRedirects:(unsigned long long)arg1 ;
-(NSURLConnection *)connection;
-(void)setConnection:(NSURLConnection *)arg1 ;
@end

