/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDictionary, NSMutableDictionary;

@interface USUserAttributes : NSObject {

	NSDictionary* _bundleUserAttributes;
	NSMutableDictionary* _userAttributes;

}

@property (nonatomic,retain) NSMutableDictionary * userAttributes;              //@synthesize userAttributes=_userAttributes - In the implementation block
@property (readonly) NSDictionary * bundleUserAttributes;                       //@synthesize bundleUserAttributes=_bundleUserAttributes - In the implementation block
+(id)sharedUserAttributes;
+(void)clearUserAttributes;
+(id)stringForKey:(id)arg1 ;
+(id)dictionaryRepresentation;
+(id)numberForKey:(id)arg1 ;
+(void)setNumber:(id)arg1 forKey:(id)arg2 ;
+(void)setString:(id)arg1 forKey:(id)arg2 ;
-(void)setUserAttributes:(NSMutableDictionary *)arg1 ;
-(NSDictionary *)bundleUserAttributes;
-(BOOL)isValidValue:(id)arg1 forKey:(id)arg2 expectedValueClass:(Class)arg3 ;
-(NSMutableDictionary *)userAttributes;
-(BOOL)isValidKey:(id)arg1 ;
-(id)stringForKey:(id)arg1 ;
-(id)numberForKey:(id)arg1 ;
-(void)setNumber:(id)arg1 forKey:(id)arg2 ;
-(void)setString:(id)arg1 forKey:(id)arg2 ;
@end

