/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 8:15:17 AM Japan Standard Time
* Operating System: Version 9.1 (Build 13B143)
* Image Source: /var/mobile/Containers/Bundle/Application/3751615E-11D9-4657-82AD-52C04FE38F0D/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSTimer;

@interface USWeakTimerTarget : NSObject {

	id _target;
	SEL _selector;
	NSTimer* _timer;

}

@property (assign,nonatomic,__weak) id target;                    //@synthesize target=_target - In the implementation block
@property (assign,nonatomic) SEL selector;                        //@synthesize selector=_selector - In the implementation block
@property (assign,nonatomic,__weak) NSTimer * timer;              //@synthesize timer=_timer - In the implementation block
-(void)fire;
-(void)setTarget:(id)arg1 ;
-(void)setSelector:(SEL)arg1 ;
-(id)target;
-(SEL)selector;
-(void)setTimer:(NSTimer *)arg1 ;
-(NSTimer *)timer;
@end

